Repository vmware/powershell-module-for-vmware-cloud-foundation-logging-management, pull requests merged in 2025-06, with the labels that each got.

#14 chore(gh): update workflows
  .github/workflows/docs.yml
  .github/workflows/issues.yml
  .github/workflows/lock.yml
  .github/workflows/pull-requests.yml
  .github/workflows/release.yml
  .github/workflows/stale.yml
  .github/workflows/tests.yml
  .gitignore
Labels: chore, github-actions, needs-review

#15 chore: update coc
  CODE_OF_CONDUCT.md
Labels: documentation, chore, needs-review

#16 chore: update readme
  README.md
Labels: documentation, chore, needs-review

#17 chore: update license
  LICENSE
  NOTICE
Labels: chore, needs-review

#21 chore: update copyright and spdx
  Makefile
  VMware.CloudFoundation.LoggingManagement.psd1
  VMware.CloudFoundation.LoggingManagement.psm1
Labels: chore

#22 docs: update supported versions
  .github/ISSUE_TEMPLATE/bug.yml
  README.md
  docs/index.md
Labels: documentation, chore, needs-review

#25 docs: sanitize examples
  VMware.CloudFoundation.LoggingManagement.psd1
  VMware.CloudFoundation.LoggingManagement.psm1
  docs/documentation/functions/Publish-EsxiLoggingConfig.md
Labels: documentation, needs-review
